### PR TITLE
Set FFTW lower compat bound to v1.7

### PR DESCRIPTION
**Pull request by jishnub**
This fixes breakages introduced by FFTW v1.7, and makes tests pass locally for me on Linux. It also simplifies types, and gets rid of hack-y workarounds for compatibility with FFTW v1.6.

### CODE REVIEW

**Comment by jishnub** [comment]
@dlfivefifty this should be good to merge

**Comment by jishnub** [comment]
Bump, would be good to have this merged

**Comment by jishnub** [comment]
Bump

**Comment by dlfivefifty** [comment]
Are we sure this isn't a breaking change?

**Comment by jishnub** [comment]
This is a bugfix, as no working code will be broken if they can't upgrade to this version, and currently broken code using FFTW v1.7 and this package will be fixed by this upgrade.

**Pull request merged**
