### PR TITLE
Fix type-promotion in BigInt transforms

### PR DESCRIPTION
**Pull request by jishnub**
On master
```julia
julia> r = big(10)^400 .+ (0:1);

julia> chebyshevtransform(r)
2-element Vector{Float64}:
  Inf
 NaN
```
This PR fixes this.

### CODE REVIEW

**Comment by jishnub** [comment]
Gentle bump @MikaelSlevinsky

**Comment by MikaelSlevinsky** [comment]
Look good!

**Comment by jishnub** [comment]
Good to merge?

**Comment by jishnub** [comment]
bump

**Comment by dlfivefifty** [comment]
@jishnub please feel free to merge things like this

**Comment by jishnub** [comment]
I don't have merge permissions on this repo

**Comment by jishnub** [comment]
@dlfivefifty there are several other outstanding PRs that should be good to go. Would you mind granting me the merge right to this repo?

**Pull request merged**
