### PR TITLE
Make chebyshev transforms type stable, make points lazy

### PR DESCRIPTION
**Pull request by dlfivefifty**

### CODE REVIEW

**Comment by dlfivefifty** [comment]
@MikaelSlevinsky Any opinions? I decided to make the code type-stable, mostly because the Julia compiler is a lot faster when it doesn't need to deal with un-inferred code. So this will help down-stream packages compile time.

I also removed support for transforming empty vectors, or for just single-point Chebyshev of the 2nd kind. I'm not sure if the latter is actually used anywhere anymore. For empty vectors, this can probably be done with an extra check in ApproxFun.

There are alternative ways to work around this if we decide empty vectors is important to support.

**Comment by MikaelSlevinsky** [comment]
How is it an improvement to remove the empty array checking? Some folks might be using the points/transforms for modified moment-based quadrature independent of JuliaApproximation. If we don’t want the execution case, then maybe put an assertion in the plan creation?

**Comment by dlfivefifty** [comment]
For the 1st kind transforms: its not an improvement, but is because FFTW throws errors iwth empty arrays
```julia
julia> dct(Float64[])
ERROR: FFTW could not create plan
```
So then we can't create a plan. This gives the following options:
1. Make the field `plan::Union{Nothing,FFTW.r2rFFTWPlan{...}}`. This should have no penalty, and still be type-stable via 
```julia
isnothing(F.plan) ? copy(x) : something(F.plan) * copy(x)
```
But it slightly complicates things.
2. Don't initialise `F.plan`. This means `F.plan` gives an undefined error. So the above becomes:
```julia
!isdefined(F, :plan) ? copy(x) : F.plan * copy(x)
```
3. Add a parameter `n::Int` and check if `n = 0`.
4. Just throw an error. This is as you say annoying, but consistent with FFTW.

Any preference between the 4 options?

For the 2nd kind transform, I don't think we want it the check on `n == 1` makes `getindex` slower for `ChebyshevGrid{2}`. And it's not clear to me that we should making a definition when its not really defined, so throwing an error is probably the right thing to do here.

**Comment by dlfivefifty** [comment]
> If we don’t want the execution case, then maybe put an assertion in the plan creation? 

This assertion already happens in FFTW.

**Comment by MikaelSlevinsky** [comment]
Ok you can decide. (I won’t be able to merge this week.)

**Pull request merged**
