### PR TITLE
separate out windows CI tasks

### PR DESCRIPTION
**Pull request by jishnub**
Separating out the windows CI runs from the mac/linux ones will continue the latter even if the windows ones fail, and unlike continue-on-error, this won't report a success result status if tasks fail.

Once https://github.com/JuliaLang/julia/pull/50135 is backported, perhaps we should run the tests for WIndows only on Julia v1.9.2+

### CODE REVIEW

**Comment by MikaelSlevinsky** [comment]
This is good, but feel free to take it a step further and have a separate ci.yml for Windows, with separate badge too, until things are back ported and settle down.

**Comment by jishnub** [comment]
Updated, and I've removed the Windows test on Julia v1.7, as that won't get fixed

**Comment by jishnub** [comment]
Gentle bump

**Comment by jishnub** [comment]
Gentle bump. The tests all pass now, with the windows tests disabled on Julia versions <v1.9.2

**Comment by jishnub** [comment]
Bump @dlfivefifty @MikaelSlevinsky

**Pull request merged**
